// Extracts the official brand paths used by the site from simple-icons into a
// small local module so the full icon set is never bundled.
const fs = require('fs');
const si = require('simple-icons');
const pick = {
  react: 'siReact', typescript: 'siTypescript', javascript: 'siJavascript',
  nodejs: 'siNodedotjs', fastapi: 'siFastapi', php: 'siPhp', docker: 'siDocker', kubernetes: 'siKubernetes',
  mysql: 'siMysql', postgresql: 'siPostgresql', mongodb: 'siMongodb', grafana: 'siGrafana',
  linux: 'siLinux', git: 'siGit', vite: 'siVite', tailwindcss: 'siTailwindcss',
};
const out = {};
for (const [k, n] of Object.entries(pick)) out[k] = { title: si[n].title, hex: '#' + si[n].hex, path: si[n].path };
// Brands not distributed by simple-icons: simplified marks.
out.oracle = { title: 'Oracle', hex: '#F80000', path: 'M7 5.5h10a6.5 6.5 0 0 1 0 13H7a6.5 6.5 0 0 1 0-13Zm0 2.75a3.75 3.75 0 0 0 0 7.5h10a3.75 3.75 0 0 0 0-7.5Z' };
out.sqlserver = { title: 'SQL Server', hex: '#CC2927', path: 'M12 2C7.03 2 3 3.57 3 5.5v13C3 20.43 7.03 22 12 22s9-1.57 9-3.5v-13C21 3.57 16.97 2 12 2Zm0 2c4.14 0 7 1.18 7 1.5S16.14 7 12 7 5 5.82 5 5.5 7.86 4 12 4ZM5 8.2C6.66 8.97 9.2 9.4 12 9.4s5.34-.43 7-1.2v3.3c0 .32-2.86 1.5-7 1.5s-7-1.18-7-1.5Zm0 6c1.66.77 4.2 1.2 7 1.2s5.34-.43 7-1.2v4.3c0 .32-2.86 1.5-7 1.5s-7-1.18-7-1.5Z' };
const body = `// Auto-generated by scripts/extract-icons.cjs — do not edit by hand.\n// Brand marks sourced from simple-icons (CC0); Oracle and SQL Server are simplified marks.\n\nexport interface BrandIcon {\n  title: string;\n  hex: string;\n  path: string;\n}\n\nexport const brandIcons = ${JSON.stringify(out, null, 2)} as const satisfies Record<string, BrandIcon>;\n\nexport type BrandKey = keyof typeof brandIcons;\n`;
fs.writeFileSync('src/data/brandIcons.ts', body);
console.log('wrote', Object.keys(out).length, 'icons');
